---
# If the transparent pixel percentage in a skin is higher than this, player will be kicked.
# IMPORTANT: Keep in mind this is NOT for the visible parts of the skin, it is for the entire skin texture, which
# normally already contains a good amount of empty pixels.
percentage: 75
...